[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.19'
fuzz_runs = 1000

[invariant]
call_override = false  # Override calls
runs          = 1000    # The number of times to run the invariant tests
depth         = 100   # The number of calls to make in the invariant tests
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config